### ISSUE TITLE
Add officer photos to the About page

### ISSUE THREAD

**Issue by JennDahm** [ut-ras/ras_site_old#17] opened 2016-06-29 01:50 UTC
It would be nice to have photographs with our officer listings.

Suggestions:
- `/static/images/leaders` is a good place to put these.
- Add a field to the entries in `_data/contact.yaml` indicating the location of these photographs.
- Ideally, the photographs should be named by position, not by officer name.

**Comment by dteal** [comment] 2018-01-27 22:19
Duplicate of other image issue. Done now.

**Closed as completed by dteal** 2018-01-27 22:19 UTC
Labels: enhancement
